# Generated by Django 2.0.6 on 2018-06-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicsite', '0002_auto_20180622_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='img',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
