# Generated by Django 2.0.6 on 2018-06-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicsite', '0003_auto_20180622_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
