# Generated by Django 2.0.6 on 2018-06-22 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicsite', '0004_auto_20180622_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebook',
            old_name='userna',
            new_name='username',
        ),
    ]
